### PR TITLE
Fixed word wrap issue so words don't break in the middle - Closes #39

### LINKED ISSUE #39: Fix word wrap issue on spike cards and admin spike cards so words don't cut off in the middle.

### PR DESCRIPTION
**Pull request by kccrs**
## Purpose
This PR fixes a UI issue where words were breaking inside the spike card and admin spike card containers.

## Approach
I changed the overflow-wrap and word-wrap CSS properties to "normal" instead of "break-word".  I also removed the word-break property as it was not needed.

## Pre merge questions and TODOs:
None, this PR is ready to merge pending code review.

### CODE REVIEW

**Comment by swanie21** [comment]
@kccrs Have you checked what the cards look like on mobile? I think we had to add the "word-break" property since it was doing something funky with the padding on the cards. They weren't the same size anymore even though they had a specified width.

**Comment by kccrs** [comment]
Ah, no I haven't!  Let me check that now... good catch!

**Comment by kccrs** [comment]
Yeah there are some issues there... I will re-configure with media queries.

**Comment by kccrs** [comment]
Ok it should be good now.  I didn't have to create a media query for it.  I just added word-break back in but set it to "normal" as well.

**Comment by swanie21** [comment]
Ok great, thanks for fixing the responsive design, should be good to merge!

File: lib/components/Spike.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ const Spike = ({ spike, createSpike, updateCount, toggleForm, user }, key, admin
         <p>Description: <span>{spike.description}</span></p>
         <p>
         Spike Session Date:
-          <span>{moment(spike.spikeDate).format('MM-DD-YYYY')}</span>
+          <span>  {moment(spike.spikeDate).format('MM-DD-YYYY')}</span>
```
Comment (kccrs) [inline lib/components/Spike.js]: Oh yeah, also I just added some space here as the text was smushed together.
